// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqnlhnowrkvnemsndwbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxbmxobm93cmt2bmVtc25kd2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MDQ4NzEsImV4cCI6MjA3MjE4MDg3MX0.ljrvF1IwbUcFqmsI8pKfysdg4HbyrcINThQ03NnxrXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});